version: 1

profiles:
  public_edge_main:
    type: wildcard
    dns_names:
      - "*.whisper.cl"
    acme:
      challenge: dns-01
      credentials: cloudflare/whisper-cl
    renew_before: 720h

hosts:
  pvvl-edge01:
    identity: pvvl-edge01.h.int.whisper.cl
    profiles:
      - public_edge_main
